### ISSUE TITLE
Cleaning up READ ME

### ISSUE THREAD

**Issue by JaeDukSeo** [full-stack-deep-learning/course-gitbook#3]
Love this course! 

Just one thing, would the links in read me be cleaned up?

have a nice day!

**Comment by josh-tobin** [comment]
All the links appear to work for me -- can you be more specific which ones aren't working?

**Comment by xbno** [comment]
Hey, it seems like we're both unfamiliar with a gitbook pluggin that the README.md formatting expects. I am seeing a lot of lines similar to this : `{% page-ref page="course-content/setting-up-machine-learning-projects/" %}`. Can you point me to/explain how you typically browse a repo like this? Thanks

Nevermind! Looks like the WebUI is here: https://course.fullstackdeeplearning.com/ I had only seen the github link on reddit and didn't know.

**Comment by josh-tobin** [comment]
Cool - I'm going to close this for now.
